### ISSUE TITLE
Explain how dcw simplifies life

### ISSUE THREAD

**Issue by bonndan** [rezzza/dcw#8]
Maybe there's some info missing on how dcw helps using docker. I wasn't able to understand it by the given example. Perhaps some "before/after" examples would be nice. Thx.

**Comment by shouze** [comment]
@bonndan you're right, could be a short paragraph of the README. In fact when using & running dcw either with `-v` or `-d` option it prints the executed docker-compose command, so maybe some examples of that kind?

**Comment by shouze** [comment]
@bonndan also [unit tests](https://github.com/rezzza/dcw/blob/master/tests/dcw.bats#L78-L80) illustrate pretty well produced docker-compose commands.

**Comment by shouze** [comment]
@bonndan could be in a `Why dcw?` section. What about that?

# Why dcw?

To sum up, do you prefer to run this kind of command when you localy develop some service on your local machine:

```shell
docker-compose --file tests/fixtures/docker-compose.yml run --no-deps --service-ports \
--rm my-service my-service-command
```

or simply use this shorthand syntax:
```shell
dcw -p my-service-command
```

**Comment by shouze** [comment]
#11 should fix this issue.

**Comment by bonndan** [comment]
cool!
